
# https://docs.docker.com/compose/compose-file/

version: "3"
services:
    db:
        image: postgres:12
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: 
            POSTGRES_USER: 
            POSTGRES_PASSWORD: 
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data/pgdata
volumes:
    postgres:   
